all: test

#target to generate an executable from the object files
test: linked_list.o use_linked_list.o
	gcc -Wall -o test linked_list.o use_linked_list.o

#target to generate an object files from c files
linked_list.o: linked_list.h linked_list.c
	gcc -Wall -c linked_list.c

use_linked_list.o: linked_list.h use_linked_list.c
	gcc -Wall -c use_linked_list.c

#target to compile the object files only
compileonly: linked_list.o use_linked_list.o

#target to delete the object files
deleteofiles:
	rm -f *.o

#target to delete the executable
deleteexec:
	rm -f test	

deleteall: deleteexec deleteofiles